### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [Swaelo/mmo-server-2.0#1]
Hello, under what license is this project released under ? I would like to study it to learn more about making my own MMO server. Thank-you.

**Comment by Swaelo** [comment]
You can do whatever you like with it

**Comment by suprafun** [comment]
Thank-you so very much, if its possible could you please add a formal license to the repo. ( of whatever you desire , MIT , BSD , GPL etc. ) ?  I would just like to be sure of what I should do. Thank-you again.

**Comment by Swaelo** [comment]
I'll set up a proper license and stuff today

**Comment by Swaelo** [comment]
MIT License has been added to the mmo-server and mmo-client projects.  
Supra I'd love for you to join my discord server to get any questions/feedback you have about the project after you take a look at it.  
Specifically, if you have any problems getting things running properly after trying to follow the setup instructions that I've given that would be super helpful as then I can make changes to the setup guide for other people in the future.

**Comment by Swaelo** [comment]
MIT License has been added to the mmo-server and mmo-client projects.  
Supra I'd love for you to join my discord server to get any questions/feedback you have about the project after you take a look at it.  (just go to swaelo.com/discord/ and you will get an invite)
Specifically, if you have any problems getting things running properly after trying to follow the setup instructions that I've given that would be super helpful as then I can make changes to the setup guide for other people in the future.
